name: CI / Deploy to Firebase Hosting

on:
  push:
    branches: ["master", "main"]
    paths:
      - "frontend/**"
      - "firebase.json"
      - "firestore.rules"
      - "firestore.indexes.json"
  pull_request:
    branches: ["master", "main"]
    paths:
      - "frontend/**"
      - "firebase.json"
      - "firestore.rules"
      - "firestore.indexes.json"

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: |
          echo "Node version:" && node --version || true
          echo "NPM version:" && npm --version || true
          echo "Attempting 'npm ci' (preferred)..."
          if npm ci; then
            echo "npm ci succeeded"
          else
            echo "npm ci failed — showing npm debug log tail and falling back to npm install --legacy-peer-deps"
            echo "---- npm debug log (tail) ----"
            tail -n 200 /home/runner/.npm/_logs/*.log || true
            echo "---- end log ----"
            npm install --legacy-peer-deps
          fi

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

      - name: Install Firebase CLI
        run: npm install -g firebase-tools@latest

      - name: Deploy to Firebase (Hosting + Firestore rules & indexes)
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          firebase deploy --only hosting,firestore:rules,firestore:indexes --project hobbymap-scuba-dive
