name: CI / Deploy to Firebase Hosting

on:
  push:
    branches: ["master", "main"]
    paths:
      - "frontend/**"
      - "firebase.json"
      - "firestore.rules"
      - "firestore.indexes.json"
  pull_request:
    branches: ["master", "main"]
    paths:
      - "frontend/**"
      - "firebase.json"
      - "firestore.rules"
      - "firestore.indexes.json"

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: "deploy-${{ github.ref }}"
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Cache frontend node_modules
        uses: actions/cache@v4
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install frontend dependencies (reproducible)
        working-directory: ./frontend
        run: |
          echo "Node version:" && node --version || true
          echo "NPM version:" && npm --version || true
          echo "Running 'npm ci --legacy-peer-deps' for reproducible installs..."
          npm ci --legacy-peer-deps

      - name: Build frontend
        working-directory: ./frontend
        # Inject build-time Firebase config from repository secrets so we
        # don't have to commit API keys to the repository. If a secret is
        # not present, the step will still run and the app will fall back
        # to the default values embedded in `frontend/src/firebase.js`.
        env:
          REACT_APP_FIREBASE_API_KEY: ${{ secrets.REACT_APP_FIREBASE_API_KEY }}
          REACT_APP_FIREBASE_AUTH_DOMAIN: ${{ secrets.REACT_APP_FIREBASE_AUTH_DOMAIN }}
          REACT_APP_FIREBASE_PROJECT_ID: ${{ secrets.REACT_APP_FIREBASE_PROJECT_ID }}
          REACT_APP_FIREBASE_STORAGE_BUCKET: ${{ secrets.REACT_APP_FIREBASE_STORAGE_BUCKET }}
          REACT_APP_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.REACT_APP_FIREBASE_MESSAGING_SENDER_ID }}
          REACT_APP_FIREBASE_APP_ID: ${{ secrets.REACT_APP_FIREBASE_APP_ID }}
          REACT_APP_FIREBASE_MEASUREMENT_ID: ${{ secrets.REACT_APP_FIREBASE_MEASUREMENT_ID }}
        run: npm run build

      - name: Install Firebase CLI (pinned)
        run: npm install -g firebase-tools@11.0.0

      - name: Deploy to Firebase (Hosting + Firestore rules & indexes)
        working-directory: ./frontend
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          # Allow overriding the project via the secret FIREBASE_PROJECT_ID.
          # If not set, default to the existing project id so current behavior is preserved.
          DEPLOY_PROJECT=${{ secrets.FIREBASE_PROJECT_ID }}
          DEPLOY_PROJECT=${DEPLOY_PROJECT:-hobbymap-scuba-dive}
          echo "Deploying to project: $DEPLOY_PROJECT"
          # Run firebase deploy in non-interactive mode so the CI run doesn't
          # stall on interactive prompts (for example index deletions). If you
          # intentionally want to remove indexes, run the deploy locally with
          # the --force flag or manage indexes through the Firebase console.
          firebase deploy --only hosting,firestore:rules,firestore:indexes --project "$DEPLOY_PROJECT" --token "$FIREBASE_TOKEN" --non-interactive
